config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  resources :planetary_systems

  delete '/removeImage/:id', to: 'planetary_systems#removeImage',
          as: 'removeImage'

  get "*path", to: redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/planetary_system.rb
class PlanetarySystem < ApplicationRecord
  belongs_to :user
  mount_uploader :image, PictureUploader
  validates :name, presence: true, length: { minimum: 3, maxium: 30}
  validates :description, length: {maximum: 1500}
  validates :age, numericality: { only_integer: true , greater_than_or_equal_to: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :planetary_systems
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/planetary_systems_controller.rb
class PlanetarySystemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @planetarySystems = PlanetarySystem.all
  end

  def show
    @planetarySystem = PlanetarySystem.find(params[:id])
  end

  def new
    @planetarySystem = current_user.planetary_systems.build
  end

  def edit
    @planetarySystem = PlanetarySystem.find(params[:id])
    if current_user.id != @planetarySystem.user.id
      redirect_to root_path
    end
  end

  def removeImage
    @planetarySystem = PlanetarySystem.find(params[:id])
    @planetarySystem.remove_image!
    @planetarySystem.save
    redirect_to @planetarySystem
  end

  def create
    @planetarySystem = current_user.planetary_systems.build(system_params)

    if @planetarySystem.save
      flash[:notice] = 'Planetary system added!'
      redirect_to @planetarySystem
    else
      flash[:error] = 'Failed to add planetary system!'
      render 'new'
    end
  end

  def update
    @planetarySystem = PlanetarySystem.find(params[:id])

    if @planetarySystem.update(system_params)
      flash[:notice] = 'Planetary system updated!'
      redirect_to @planetarySystem
    else
      flash[:error] = 'Failed to edit planetary system!'
      render 'edit'
    end
  end

  def destroy
    @planetarySystem = PlanetarySystem.find(params[:id])
    if current_user.id != @planetarySystem.user.id
      redirect_to root_path
    end

    if @planetarySystem.destroy
      flash[:notice] = 'Planetary system deleted!'
      redirect_to planetary_systems_path
    else
      flash[:error] = 'Failed to delete this planetary system!'
      render :destroy
    end
  end

  private
    def system_params
      params.require(:planetary_system).permit(:name, :age, :image, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Project#1"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/planetary_systems_helper.rb
module PlanetarySystemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Space Database", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Home",    root_path %>
        </li>
        <li>
          <%= link_to "Planetary Systems", planetary_systems_path %>
        </li>
        <% if user_signed_in? %>
        <li>
          <%= link_to 'New planetary system', new_planetary_system_path %>
        </li>
        <% end %>
        <% if !user_signed_in? %>
        <li>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
        <% end %>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        </li>
        <% else %>
        <li>
          <%= link_to "Log in", new_user_session_path %>
        </li>
        <% end %>      
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/planetary_systems/_form.html.erb
<div class='container-fluid new_container'>
  <%= form_for @planetarySystem do |f| %>

  <% if @planetarySystem.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@planetarySystem.errors.count, "error") %> prohibited
        this planetary system from being saved:
      </h3>
      <% @planetarySystem.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <strong>Warning!</strong> <%= msg %>
      </div>
      <% end %>
    </div>
  <% end %>

  <div class='form-group row'>
    <%= f.label :name, class: 'col-2 col-form-label' %>
    <div class='col-10'>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group row'>
    <%= f.label :age, class: 'col-2 col-form-label' %><br>
    <div class='col-10'>
      <%= f.number_field :age, class: 'form-control', min: 0 %>
    </div>
  </div>

  <div class='form-group row'>
    <%= f.label :description, class: 'col-2 col-form-label' %>
      <%= md_simple_editor do %>
        <%= f.text_area :description, as: :text %>
      <% end %>
  </div>

  <div class='form-group row'>
    <%= f.label :image, class: 'col-2 col-form-label' %><br>
    <div class='col-10'>
      <%= f.file_field :image, onchange: "validateFiles(this);", data: { max_file_size: 5.megabytes },
      class: 'form-control', dragdrop: true %>
        <br><p>
        <%= f.submit class: 'btn btn-primary' %>
      </p>
    </div>
  </div>



  <% end %>
</div>

app/views/planetary_systems/edit.html.erb
<div class='container'>
  <h1>Editing planetary system</h1>

<%= render 'form' %>

</div>

app/views/planetary_systems/index.html.erb
<div class='page-header'>
  <h1>Planetary systems</h1>
</div>

<% if flash[:notice] %>
<div class="alert alert-info">
  <strong>Info!</strong> <%= flash[:notice] %>
</div>
<% end %>

<div class='container-fluid'>
  <div class='row'>
    <div class='col-md-10 col-sm-12'>
      <div class='row'>
        <% @planetarySystems.each do |system| %>
        <div class='systems_block col-md-4 col-sm-6 col-xs-12' >
          <div class='row'>
            <div class='col-md-5 col-sm-5 col-xs-12'><%= image_tag(system.image_url(:thumbnail)) %></div>
            <div class='col-md-7 col-sm-7 col-xs-12'><h3><%= system.name %></h3>
              <p>Age: <%= system.age %>
                <% if system.age > 1  %>
                mld years
                <% else %>
                mld year
                <% end %></p>
                <p class='options'><%= link_to 'Show', planetary_system_path(system) %></div>
                </div>
              </div>
              <% end %>
            </div>
          </div>
          <div class='col-md-1 col-sm-0'></div>
        </div>

app/views/planetary_systems/new.html.erb
<div class='container'>
<h1> New planetary system </h1>

<%= render 'form' %>

<button type="button" class="new_system btn btn-primary">
  <%= link_to 'Back', planetary_systems_path %>
</button>
</div>

app/views/planetary_systems/show.html.erb
<div class='container-fluid'>

  <div class='row'>
    <div class='col-md-1 col-sm-10'></div>
    <div class='col-md-5 col-sm-10'>
      <%= image_tag(@planetarySystem.image_url(:standard)) %>
    </div>
    <div class='col-md-5 col-sm-10'>
      <% if flash[:notice] %>
      <div class="alert alert-info">
        <strong>Info!</strong> <%= flash[:notice] %>
      </div>
      <% end %>
      <div class='page-header'>
        <h2><%= @planetarySystem.name %></h2>
        <small>
          Added by <%= @planetarySystem.user.email %>
          <%= time_ago_in_words(@planetarySystem.created_at) %> ago
        </small>
      </div>

      <h4>
        <strong>Age:</strong>
        <%= @planetarySystem.age %>
        <% if @planetarySystem.age > 1  %>
        mld years
        <% else %>
        mld year
        <% end %></p>
      </h4>
      <h4><strong>Description: </strong></h4>
      <p> <%= @planetarySystem.description %> </p>
      <div>
        <% if user_signed_in? %>
        <% if @planetarySystem.user.id == current_user.id %>
        <%= link_to 'Edit', edit_planetary_system_path(@planetarySystem), class: "btn btn-primary"  %>
        <%= link_to 'Destroy', planetary_system_path(@planetarySystem),
        method: :delete,
        data: { confirm: 'Are you sure?' }, class: "btn btn-primary"   %>
        <% end %>
        <% end %>
        <%= link_to 'Back', planetary_systems_path, class: "btn btn-primary" %>
      </div>
      <div class='col-md-1 col-sm-10'></div>
    </div>
  </div>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>

</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>

</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class='row'>
  <div class='col-md-3 col-sm-0'></div>
  <div class='col-md-6 col-sm-12'>
    <div class="center jumbotron">
      <h3>Adrian Porębski (zaliczenie)</h3>

      <h4>Temat: Space Database</h4>

      <p>Space Database umożliwia dodawanie nowych systemów planetarnych do bazy danych. System może
        zawierać takie informacje jak nazwa, wiek, opis oraz poglądowe zdjęcie. Aby dodać bądź edytować wcześniej przez siebie dodany system, należy założyć konto. Dodanie systemu uprawnia
        do jego edycji bądź usunięcia.</p>

        <h5>Gemy:</h5>
        <ul>
          <li>carrierwave: gem pozwalając dodawać grafiki</li>
          <li>mini_magick: gem służący do skalowania obrazków</li>
          <li>md_simple_editor: edytor tekstowy pozwalający w bardziej zaawansowany sposób edytować opisy</li>
        </ul>
      </div>
    </div>
    <div class='col-md-3 col-sm-0'></div>
  </div>